// ===============================
// JEWELLERY IMAGE LIST
// ===============================

const jewelleryImages = {

  // ===============================
  // GOLD
  // ===============================

  gold: {

    // ===============================
    // GENTS
    // ===============================

    gents: {

      rings: [
        "images/gold/gents/rings/ring-1.jpg",
        "images/gold/gents/rings/ring-2.jpg",
        "images/gold/gents/rings/ring-3.jpg",
        "images/gold/gents/rings/ring-4.jpg",
        "images/gold/gents/rings/ring-5.jpg",
        "images/gold/gents/rings/ring-6.jpg",
        "images/gold/gents/rings/ring-7.jpg",
        "images/gold/gents/rings/ring-8.jpg",
        "images/gold/gents/rings/ring-9.jpg",
        "images/gold/gents/rings/ring-10.jpg",
        "images/gold/gents/rings/ring-11.jpg",
        "images/gold/gents/rings/ring-12.jpg",
        "images/gold/gents/rings/ring-13.jpg",
        "images/gold/gents/rings/ring-14.jpg",
        "images/gold/gents/rings/ring-15.jpg",
        "images/gold/gents/rings/ring-16.jpg",
        "images/gold/gents/rings/ring-17.jpg",
        "images/gold/gents/rings/ring-18.jpg",
        "images/gold/gents/rings/ring-19.jpg",
        "images/gold/gents/rings/ring-20.jpg",
        "images/gold/gents/rings/ring-21.jpg",
        "images/gold/gents/rings/ring-22.jpg",
        "images/gold/gents/rings/ring-23.jpg",
        "images/gold/gents/rings/ring-24.jpg",
        "images/gold/gents/rings/ring-25.jpg",
        "images/gold/gents/rings/ring-26.jpg",
        "images/gold/gents/rings/ring-27.jpg",
        "images/gold/gents/rings/ring-28.jpg",
        "images/gold/gents/rings/ring-29.jpg",
        "images/gold/gents/rings/ring-30.jpg",
        "images/gold/gents/rings/ring-31.jpg",
        "images/gold/gents/rings/ring-32.jpg",
        "images/gold/gents/rings/ring-33.jpg",
        "images/gold/gents/rings/ring-34.jpg"
      ],

      bracelets: [
        "images/gold/gents/bracelets/bracelet-01.jpg",
        "images/gold/gents/bracelets/bracelet-02.jpg",
        "images/gold/gents/bracelets/bracelet-03.jpg",
        "images/gold/gents/bracelets/bracelet-04.jpg",
        "images/gold/gents/bracelets/bracelet-05.jpg",
        "images/gold/gents/bracelets/bracelet-06.jpg",
        "images/gold/gents/bracelets/bracelet-07.jpg",
        "images/gold/gents/bracelets/bracelet-08.jpg",
        "images/gold/gents/bracelets/bracelet-09.jpg",
        "images/gold/gents/bracelets/bracelet-10.jpg",
        "images/gold/gents/bracelets/bracelet-11.jpg",
        "images/gold/gents/bracelets/bracelet-12.jpg",
        "images/gold/gents/bracelets/bracelet-13.jpg",
        "images/gold/gents/bracelets/bracelet-14.jpg",
        "images/gold/gents/bracelets/bracelet-15.jpg",
        "images/gold/gents/bracelets/bracelet-16.jpg",
        "images/gold/gents/bracelets/bracelet-17.jpg",
        "images/gold/gents/bracelets/bracelet-18.jpg",
        "images/gold/gents/bracelets/bracelet-19.jpg",
        "images/gold/gents/bracelets/bracelet-20.jpg",
        "images/gold/gents/bracelets/bracelet-21.jpg",
        "images/gold/gents/bracelets/bracelet-22.jpg",
        "images/gold/gents/bracelets/bracelet-23.jpg",
        "images/gold/gents/bracelets/bracelet-24.jpg",
        "images/gold/gents/bracelets/bracelet-25.jpg",
        "images/gold/gents/bracelets/bracelet-26.jpg",
        "images/gold/gents/bracelets/bracelet-27.jpg",
        "images/gold/gents/bracelets/bracelet-28.jpg",
        "images/gold/gents/bracelets/bracelet-29.jpg",
        "images/gold/gents/bracelets/bracelet-30.jpg"
      ],


      chains: [
        "images/gold/gents/chains/chain-01.jpg",
        "images/gold/gents/chains/chain-02.jpg",
        "images/gold/gents/chains/chain-03.jpg",
        "images/gold/gents/chains/chain-04.jpg",
        "images/gold/gents/chains/chain-05.jpg",
        "images/gold/gents/chains/chain-06.jpg",
        "images/gold/gents/chains/chain-07.jpg",
        "images/gold/gents/chains/chain-08.jpg",
        "images/gold/gents/chains/chain-09.jpg",
        "images/gold/gents/chains/chain-10.jpg",
        "images/gold/gents/chains/chain-11.jpg",
        "images/gold/gents/chains/chain-12.jpg",
        "images/gold/gents/chains/chain-13.jpg",
        "images/gold/gents/chains/chain-14.jpg",
        "images/gold/gents/chains/chain-15.jpg",
        "images/gold/gents/chains/chain-16.jpg",
        "images/gold/gents/chains/chain-17.jpg",
        "images/gold/gents/chains/chain-18.jpg",
        "images/gold/gents/chains/chain-19.jpg",
        "images/gold/gents/chains/chain-20.jpg",
        "images/gold/gents/chains/chain-21.jpg",
        "images/gold/gents/chains/chain-22.jpg",
        "images/gold/gents/chains/chain-23.jpg",
        "images/gold/gents/chains/chain-24.jpg",
        "images/gold/gents/chains/chain-25.jpg",
        "images/gold/gents/chains/chain-26.jpg",
        "images/gold/gents/chains/chain-27.jpg",
        "images/gold/gents/chains/chain-28.jpg",
        "images/gold/gents/chains/chain-29.jpg",
        "images/gold/gents/chains/chain-30.jpg",
        "images/gold/gents/chains/chain-31.jpg",
        "images/gold/gents/chains/chain-32.jpg",
        "images/gold/gents/chains/chain-33.jpg",
        "images/gold/gents/chains/chain-34.jpg",
        "images/gold/gents/chains/chain-35.jpg",
        "images/gold/gents/chains/chain-36.jpg",
        "images/gold/gents/chains/chain-37.jpg",
        "images/gold/gents/chains/chain-38.jpg",
        "images/gold/gents/chains/chain-39.jpg",
        "images/gold/gents/chains/chain-40.jpg",
        "images/gold/gents/chains/chain-41.jpg",
        "images/gold/gents/chains/chain-42.jpg",
        "images/gold/gents/chains/chain-43.jpg",
        "images/gold/gents/chains/chain-44.jpg",
        "images/gold/gents/chains/chain-45.jpg",
        "images/gold/gents/chains/chain-46.jpg",
        "images/gold/gents/chains/chain-47.jpg",
        "images/gold/gents/chains/chain-48.jpg",
        "images/gold/gents/chains/chain-49.jpg",
        "images/gold/gents/chains/chain-50.jpg",
        "images/gold/gents/chains/chain-51.jpg",
        "images/gold/gents/chains/chain-52.jpg",
        "images/gold/gents/chains/chain-53.jpg",
        "images/gold/gents/chains/chain-54.jpg",
        "images/gold/gents/chains/chain-55.jpg",
        "images/gold/gents/chains/chain-56.jpg",
        "images/gold/gents/chains/chain-57.jpg",
        "images/gold/gents/chains/chain-58.jpg",
        "images/gold/gents/chains/chain-59.jpg",
        "images/gold/gents/chains/chain-60.jpg",
        "images/gold/gents/chains/chain-61.jpg",
        "images/gold/gents/chains/chain-62.jpg",
        "images/gold/gents/chains/chain-63.jpg",
        "images/gold/gents/chains/chain-64.jpg",
        "images/gold/gents/chains/chain-65.jpg",
        "images/gold/gents/chains/chain-66.jpg",
        "images/gold/gents/chains/chain-67.jpg",
        "images/gold/gents/chains/chain-68.jpg",
        "images/gold/gents/chains/chain-69.jpg",
        "images/gold/gents/chains/chain-70.jpg",
        "images/gold/gents/chains/chain-71.jpg",
        "images/gold/gents/chains/chain-72.jpg",
        "images/gold/gents/chains/chain-73.jpg",
        "images/gold/gents/chains/chain-74.jpg",
        "images/gold/gents/chains/chain-75.jpg",
        "images/gold/gents/chains/chain-76.jpg",
        "images/gold/gents/chains/chain-77.jpg",
        "images/gold/gents/chains/chain-78.jpg",
        "images/gold/gents/chains/chain-79.jpg",
        "images/gold/gents/chains/chain-80.jpg",
        "images/gold/gents/chains/chain-81.jpg",
        "images/gold/gents/chains/chain-82.jpg",
        "images/gold/gents/chains/chain-83.jpg",
        "images/gold/gents/chains/chain-84.jpg",
        "images/gold/gents/chains/chain-85.jpg",
        "images/gold/gents/chains/chain-86.jpg",
        "images/gold/gents/chains/chain-87.jpg",
        "images/gold/gents/chains/chain-88.jpg",
        "images/gold/gents/chains/chain-89.jpg"
      ],


      "single-bali": ["images/gold/gents/single-bali/single-bali-01.jpg",
                      "images/gold/gents/single-bali/single-bali-02.jpg"  ],

      "wrist-watches": [
    "images/gold/gents/wrist-watches/wrist-watch-01.jpg",
    "images/gold/gents/wrist-watches/wrist-watch-02.jpg",
    "images/gold/gents/wrist-watches/wrist-watch-03.jpg",
    "images/gold/gents/wrist-watches/wrist-watch-04.jpg",
    "images/gold/gents/wrist-watches/wrist-watch-05.jpg",
    "images/gold/gents/wrist-watches/wrist-watch-06.jpg",
    "images/gold/gents/wrist-watches/wrist-watch-07.jpg",
    "images/gold/gents/wrist-watches/wrist-watch-08.jpg",
    "images/gold/gents/wrist-watches/wrist-watch-09.jpg",
    "images/gold/gents/wrist-watches/wrist-watch-10.jpg",
    "images/gold/gents/wrist-watches/wrist-watch-11.jpg",
    "images/gold/gents/wrist-watches/wrist-watch-12.jpg",
    "images/gold/gents/wrist-watches/wrist-watch-13.jpg",
    "images/gold/gents/wrist-watches/wrist-watch-14.jpg",
    "images/gold/gents/wrist-watches/wrist-watch-15.jpg",
    "images/gold/gents/wrist-watches/wrist-watch-16.jpg",
    "images/gold/gents/wrist-watches/wrist-watch-17.jpg",
    "images/gold/gents/wrist-watches/wrist-watch-18.jpg",
    "images/gold/gents/wrist-watches/wrist-watch-19.jpg",
    "images/gold/gents/wrist-watches/wrist-watch-20.jpg",
 
]

    },


    // ===============================
    // LADIES
    // ===============================

    ladies: {

      rings: [
        "images/gold/ladies/rings/ring-01.jpg",
        "images/gold/ladies/rings/ring-02.jpg",
        "images/gold/ladies/rings/ring-03.jpg",
        "images/gold/ladies/rings/ring-04.jpg",
        "images/gold/ladies/rings/ring-05.jpg",
        "images/gold/ladies/rings/ring-06.jpg",
        "images/gold/ladies/rings/ring-07.jpg",
        "images/gold/ladies/rings/ring-08.jpg",
        "images/gold/ladies/rings/ring-09.jpg",
        "images/gold/ladies/rings/ring-10.jpg",
        "images/gold/ladies/rings/ring-11.jpg",
        "images/gold/ladies/rings/ring-12.jpg",
        "images/gold/ladies/rings/ring-13.jpg",
        "images/gold/ladies/rings/ring-14.jpg",
        "images/gold/ladies/rings/ring-15.jpg",
        "images/gold/ladies/rings/ring-16.jpg",
        "images/gold/ladies/rings/ring-17.jpg",
        "images/gold/ladies/rings/ring-18.jpg",
        "images/gold/ladies/rings/ring-19.jpg",
        "images/gold/ladies/rings/ring-20.jpg",
        "images/gold/ladies/rings/ring-21.jpg",
        "images/gold/ladies/rings/ring-22.jpg",
        "images/gold/ladies/rings/ring-23.jpg",
        "images/gold/ladies/rings/ring-24.jpg",
        "images/gold/ladies/rings/ring-25.jpg",
        "images/gold/ladies/rings/ring-26.jpg",
        "images/gold/ladies/rings/ring-27.jpg"
      ],

      bracelets: [ 
  "images/gold/ladies/bracelets/bracelet-01.jpg",
  "images/gold/ladies/bracelets/bracelet-02.jpg",
  "images/gold/ladies/bracelets/bracelet-03.jpg"
],

      chains: [
  "images/gold/ladies/chains/ladies-chain-1.jpg",
  "images/gold/ladies/chains/ladies-chain-2.jpg",
  "images/gold/ladies/chains/ladies-chain-3.jpg",
  "images/gold/ladies/chains/ladies-chain-4.jpg",
  "images/gold/ladies/chains/ladies-chain-5.jpg",
  "images/gold/ladies/chains/ladies-chain-6.jpg",
  "images/gold/ladies/chains/ladies-chain-7.jpg",
  "images/gold/ladies/chains/ladies-chain-8.jpg",
  "images/gold/ladies/chains/ladies-chain-9.jpg",
  "images/gold/ladies/chains/ladies-chain-10.jpg",
  "images/gold/ladies/chains/ladies-chain-11.jpg",
  "images/gold/ladies/chains/ladies-chain-12.jpg",
  "images/gold/ladies/chains/ladies-chain-13.jpg",
  "images/gold/ladies/chains/ladies-chain-14.jpg",
  "images/gold/ladies/chains/ladies-chain-15.jpg",
  "images/gold/ladies/chains/ladies-chain-16.jpg",
  "images/gold/ladies/chains/ladies-chain-17.jpg",
  "images/gold/ladies/chains/ladies-chain-18.jpg",
  "images/gold/ladies/chains/ladies-chain-19.jpg",
  "images/gold/ladies/chains/ladies-chain-20.jpg",
  "images/gold/ladies/chains/ladies-chain-21.jpg",
  "images/gold/ladies/chains/ladies-chain-22.jpg",
  "images/gold/ladies/chains/ladies-chain-23.jpg",
  "images/gold/ladies/chains/ladies-chain-24.jpg",
  "images/gold/ladies/chains/ladies-chain-25.jpg",
  "images/gold/ladies/chains/ladies-chain-26.jpg",
  "images/gold/ladies/chains/ladies-chain-27.jpg",
  "images/gold/ladies/chains/ladies-chain-28.jpg",
  "images/gold/ladies/chains/ladies-chain-29.jpg",
  "images/gold/ladies/chains/ladies-chain-30.jpg",
  "images/gold/ladies/chains/ladies-chain-31.jpg",
  "images/gold/ladies/chains/ladies-chain-32.jpg",
  "images/gold/ladies/chains/ladies-chain-33.jpg",
  "images/gold/ladies/chains/ladies-chain-34.jpg",
  "images/gold/ladies/chains/ladies-chain-35.jpg",
  "images/gold/ladies/chains/ladies-chain-36.jpg",
  "images/gold/ladies/chains/ladies-chain-37.jpg"
],
                                                        
      earrings:[
     
    "images/gold/ladies/earrings/earring-28.jpg",
    "images/gold/ladies/earrings/earring-29.jpg",
    "images/gold/ladies/earrings/earring-30.jpg",
    "images/gold/ladies/earrings/earring-31.jpg",
    "images/gold/ladies/earrings/earring-32.jpg",
    "images/gold/ladies/earrings/earring-33.jpg",
    "images/gold/ladies/earrings/earring-34.jpg",
    "images/gold/ladies/earrings/earring-35.jpg",
    "images/gold/ladies/earrings/earring-36.jpg",
    "images/gold/ladies/earrings/earring-37.jpg",
    "images/gold/ladies/earrings/earring-38.jpg",
    "images/gold/ladies/earrings/earring-39.jpg",
    "images/gold/ladies/earrings/earring-40.jpg",
    "images/gold/ladies/earrings/earring-41.jpg",
    "images/gold/ladies/earrings/earring-42.jpg",
    "images/gold/ladies/earrings/earring-43.jpg",
    "images/gold/ladies/earrings/earring-44.jpg",
    "images/gold/ladies/earrings/earring-45.jpg",
    "images/gold/ladies/earrings/earring-46.jpg",
    "images/gold/ladies/earrings/earring-47.jpg",
    "images/gold/ladies/earrings/earring-48.jpg",
    "images/gold/ladies/earrings/earring-49.jpg",
    "images/gold/ladies/earrings/earring-50.jpg",
    "images/gold/ladies/earrings/earring-51.jpg",
    "images/gold/ladies/earrings/earring-52.jpg",
    "images/gold/ladies/earrings/earring-53.jpg",
    "images/gold/ladies/earrings/earring-54.jpg",
    "images/gold/ladies/earrings/earring-55.jpg",
    "images/gold/ladies/earrings/earring-56.jpg",
    "images/gold/ladies/earrings/earring-57.jpg",
    "images/gold/ladies/earrings/earring-58.jpg",
    "images/gold/ladies/earrings/earring-59.jpg",
    "images/gold/ladies/earrings/earring-60.jpg",
    "images/gold/ladies/earrings/earring-61.jpg",
    "images/gold/ladies/earrings/earring-62.jpg",
    "images/gold/ladies/earrings/earring-63.jpg",
    "images/gold/ladies/earrings/earring-64.jpg",
    "images/gold/ladies/earrings/earring-65.jpg",
    "images/gold/ladies/earrings/earring-66.jpg",
    "images/gold/ladies/earrings/earring-67.jpg",
    "images/gold/ladies/earrings/earring-68.jpg",
    "images/gold/ladies/earrings/earring-69.jpg",
    "images/gold/ladies/earrings/earring-70.jpg",
    "images/gold/ladies/earrings/earring-71.jpg",
    "images/gold/ladies/earrings/earring-72.jpg",
    "images/gold/ladies/earrings/earring-73.jpg",
    "images/gold/ladies/earrings/earring-74.jpg",
    "images/gold/ladies/earrings/earring-75.jpg",
    "images/gold/ladies/earrings/earring-76.jpg",
    "images/gold/ladies/earrings/earring-77.jpg",
    "images/gold/ladies/earrings/earring-78.jpg",
    "images/gold/ladies/earrings/earring-79.jpg",
    "images/gold/ladies/earrings/earring-80.jpg",
    "images/gold/ladies/earrings/earring-81.jpg",
    "images/gold/ladies/earrings/earring-82.jpg",
    "images/gold/ladies/earrings/earring-83.jpg",
    "images/gold/ladies/earrings/earring-84.jpg",
    "images/gold/ladies/earrings/earring-85.jpg",
    "images/gold/ladies/earrings/earring-86.jpg",
    "images/gold/ladies/earrings/earring-87.jpg",
    "images/gold/ladies/earrings/earring-88.jpg",
    "images/gold/ladies/earrings/earring-89.jpg",
    "images/gold/ladies/earrings/earring-90.jpg",
    "images/gold/ladies/earrings/earring-91.jpg",
    "images/gold/ladies/earrings/earring-92.jpg",
    "images/gold/ladies/earrings/earring-93.jpg",
    "images/gold/ladies/earrings/earring-94.jpg",
    "images/gold/ladies/earrings/earring-95.jpg",
    "images/gold/ladies/earrings/earring-96.jpg",
    "images/gold/ladies/earrings/earring-97.jpg",
    "images/gold/ladies/earrings/earring-98.jpg",
    "images/gold/ladies/earrings/earring-99.jpg",
    "images/gold/ladies/earrings/earring-100.jpg",
    "images/gold/ladies/earrings/earring-101.jpg",
    "images/gold/ladies/earrings/earring-102.jpg",
    "images/gold/ladies/earrings/earring-103.jpg",
    "images/gold/ladies/earrings/earring-104.jpg",
    "images/gold/ladies/earrings/earring-105.jpg",
    "images/gold/ladies/earrings/earring-106.jpg",
    "images/gold/ladies/earrings/earring-107.jpg",
    "images/gold/ladies/earrings/earring-108.jpg",
    "images/gold/ladies/earrings/earring-109.jpg",
    "images/gold/ladies/earrings/earring-110.jpg",
    "images/gold/ladies/earrings/earring-111.jpg",
    "images/gold/ladies/earrings/earring-112.jpg",
    "images/gold/ladies/earrings/earring-113.jpg",
    "images/gold/ladies/earrings/earring-114.jpg",
    "images/gold/ladies/earrings/earring-115.jpg",
    "images/gold/ladies/earrings/earring-116.jpg",
    "images/gold/ladies/earrings/earring-117.jpg",
    "images/gold/ladies/earrings/earring-118.jpg",
    "images/gold/ladies/earrings/earring-119.jpg",
    "images/gold/ladies/earrings/earring-120.jpg",
    "images/gold/ladies/earrings/earring-121.jpg",
    "images/gold/ladies/earrings/earring-122.jpg",
    "images/gold/ladies/earrings/earring-123.jpg",
    "images/gold/ladies/earrings/earring-124.jpg",
    "images/gold/ladies/earrings/earring-125.jpg",
    "images/gold/ladies/earrings/earring-126.jpg",
    "images/gold/ladies/earrings/earring-127.jpg",
    "images/gold/ladies/earrings/earring-128.jpg",
    "images/gold/ladies/earrings/earring-129.jpg",
    "images/gold/ladies/earrings/earring-130.jpg",
    "images/gold/ladies/earrings/earring-131.jpg",
    "images/gold/ladies/earrings/earring-132.jpg",
    "images/gold/ladies/earrings/earring-133.jpg",
    "images/gold/ladies/earrings/earring-134.jpg",
    "images/gold/ladies/earrings/earring-135.jpg",
    "images/gold/ladies/earrings/earring-136.jpg",
    "images/gold/ladies/earrings/earring-137.jpg",
    "images/gold/ladies/earrings/earring-138.jpg",
    "images/gold/ladies/earrings/earring-139.jpg",
    
],

      bangles: [  
  "images/gold/ladies/bangles/bangles-1.jpg",
  "images/gold/ladies/bangles/bangles-2.jpg",
  "images/gold/ladies/bangles/bangles-3.jpg",
  "images/gold/ladies/bangles/bangles-4.jpg",
  "images/gold/ladies/bangles/bangles-5.jpg",
  "images/gold/ladies/bangles/bangles-6.jpg",
  "images/gold/ladies/bangles/bangles-7.jpg",
  "images/gold/ladies/bangles/bangles-8.jpg",
  "images/gold/ladies/bangles/bangles-9.jpg",
  "images/gold/ladies/bangles/bangles-10.jpg",
  "images/gold/ladies/bangles/bangles-11.jpg",
  "images/gold/ladies/bangles/bangles-12.jpg",
  "images/gold/ladies/bangles/bangles-13.jpg",
  "images/gold/ladies/bangles/bangles-14.jpg",
  "images/gold/ladies/bangles/bangles-15.jpg",
  "images/gold/ladies/bangles/bangles-16.jpg",
  "images/gold/ladies/bangles/bangles-17.jpg",
  "images/gold/ladies/bangles/bangles-18.jpg",
  "images/gold/ladies/bangles/bangles-19.jpg",
  "images/gold/ladies/bangles/bangles-20.jpg",
  "images/gold/ladies/bangles/bangles-21.jpg",
  "images/gold/ladies/bangles/bangles-22.jpg",
  "images/gold/ladies/bangles/bangles-23.jpg",
  "images/gold/ladies/bangles/bangles-24.jpg",
  "images/gold/ladies/bangles/bangles-25.jpg",
  "images/gold/ladies/bangles/bangles-26.jpg",
  "images/gold/ladies/bangles/bangles-27.jpg",
  "images/gold/ladies/bangles/bangles-28.jpg",
  "images/gold/ladies/bangles/bangles-29.jpg",
  "images/gold/ladies/bangles/bangles-30.jpg",
  "images/gold/ladies/bangles/bangles-31.jpg",
  "images/gold/ladies/bangles/bangles-32.jpg",
  "images/gold/ladies/bangles/bangles-33.jpg",
  "images/gold/ladies/bangles/bangles-34.jpg",
  "images/gold/ladies/bangles/bangles-35.jpg",
  "images/gold/ladies/bangles/bangles-36.jpg",
  "images/gold/ladies/bangles/bangles-37.jpg",
  "images/gold/ladies/bangles/bangles-38.jpg",
  "images/gold/ladies/bangles/bangles-39.jpg",
  "images/gold/ladies/bangles/bangles-40.jpg",
  "images/gold/ladies/bangles/bangles-41.jpg",
  "images/gold/ladies/bangles/bangles-42.jpg",
  "images/gold/ladies/bangles/bangles-43.jpg",
  "images/gold/ladies/bangles/bangles-44.jpg",
  "images/gold/ladies/bangles/bangles-45.jpg",
  "images/gold/ladies/bangles/bangles-46.jpg",
  "images/gold/ladies/bangles/bangles-47.jpg",
  "images/gold/ladies/bangles/bangles-48.jpg",
  "images/gold/ladies/bangles/bangles-49.jpg",
  "images/gold/ladies/bangles/bangles-50.jpg",
  "images/gold/ladies/bangles/bangles-51.jpg",
  "images/gold/ladies/bangles/bangles-52.jpg",
  "images/gold/ladies/bangles/bangles-53.jpg",
  "images/gold/ladies/bangles/bangles-54.jpg",
  "images/gold/ladies/bangles/bangles-55.jpg",
  "images/gold/ladies/bangles/bangles-56.jpg",
  "images/gold/ladies/bangles/bangles-57.jpg",
  "images/gold/ladies/bangles/bangles-58.jpg",
  "images/gold/ladies/bangles/bangles-59.jpg",
  "images/gold/ladies/bangles/bangles-60.jpg",
  "images/gold/ladies/bangles/bangles-61.jpg",
  "images/gold/ladies/bangles/bangles-62.jpg",
  "images/gold/ladies/bangles/bangles-63.jpg",
  "images/gold/ladies/bangles/bangles-64.jpg",
  "images/gold/ladies/bangles/bangles-65.jpg",
  "images/gold/ladies/bangles/bangles-66.jpg",
  "images/gold/ladies/bangles/bangles-67.jpg",
  "images/gold/ladies/bangles/bangles-68.jpg",
  "images/gold/ladies/bangles/bangles-69.jpg",
  "images/gold/ladies/bangles/bangles-70.jpg",
  "images/gold/ladies/bangles/bangles-71.jpg",
  "images/gold/ladies/bangles/bangles-72.jpg",
  "images/gold/ladies/bangles/bangles-73.jpg",
  "images/gold/ladies/bangles/bangles-74.jpg",
  "images/gold/ladies/bangles/bangles-75.jpg",
  "images/gold/ladies/bangles/bangles-76.jpg",
  "images/gold/ladies/bangles/bangles-77.jpg",
  "images/gold/ladies/bangles/bangles-78.jpg",
  "images/gold/ladies/bangles/bangles-79.jpg",
  "images/gold/ladies/bangles/bangles-80.jpg",
  "images/gold/ladies/bangles/bangles-81.jpg",
  "images/gold/ladies/bangles/bangles-82.jpg",
  "images/gold/ladies/bangles/bangles-83.jpg",
  "images/gold/ladies/bangles/bangles-84.jpg",
  "images/gold/ladies/bangles/bangles-85.jpg",
  "images/gold/ladies/bangles/bangles-86.jpg",
  "images/gold/ladies/bangles/bangles-87.jpg",
  "images/gold/ladies/bangles/bangles-88.jpg",
  "images/gold/ladies/bangles/bangles-89.jpg",
  "images/gold/ladies/bangles/bangles-90.jpg",
  "images/gold/ladies/bangles/bangles-91.jpg",
  "images/gold/ladies/bangles/bangles-92.jpg",
  "images/gold/ladies/bangles/bangles-93.jpg",
  "images/gold/ladies/bangles/bangles-94.jpg",
  "images/gold/ladies/bangles/bangles-95.jpg",
  "images/gold/ladies/bangles/bangles-96.jpg",
  "images/gold/ladies/bangles/bangles-97.jpg",
  "images/gold/ladies/bangles/bangles-98.jpg",
  "images/gold/ladies/bangles/bangles-99.jpg",
  "images/gold/ladies/bangles/bangles-100.jpg"
],
mangalsutra: [
    "images/gold/ladies/mangalsutra/mangalsutra-1.jpg",
    "images/gold/ladies/mangalsutra/mangalsutra-2.jpg",
    "images/gold/ladies/mangalsutra/mangalsutra-3.jpg",
    "images/gold/ladies/mangalsutra/mangalsutra-4.jpg",
    "images/gold/ladies/mangalsutra/mangalsutra-5.jpg",
    "images/gold/ladies/mangalsutra/mangalsutra-6.jpg",
    "images/gold/ladies/mangalsutra/mangalsutra-7.jpg",
    "images/gold/ladies/mangalsutra/mangalsutra-8.jpg",
    "images/gold/ladies/mangalsutra/mangalsutra-9.jpg",
    "images/gold/ladies/mangalsutra/mangalsutra-10.jpg",
    "images/gold/ladies/mangalsutra/mangalsutra-11.jpg",
    "images/gold/ladies/mangalsutra/mangalsutra-12.jpg",
    "images/gold/ladies/mangalsutra/mangalsutra-13.jpg",
    "images/gold/ladies/mangalsutra/mangalsutra-14.jpg",
    "images/gold/ladies/mangalsutra/mangalsutra-15.jpg",
    "images/gold/ladies/mangalsutra/mangalsutra-16.jpg",
    "images/gold/ladies/mangalsutra/mangalsutra-17.jpg",
    "images/gold/ladies/mangalsutra/mangalsutra-18.jpg",
    "images/gold/ladies/mangalsutra/mangalsutra-19.jpg",
    "images/gold/ladies/mangalsutra/mangalsutra-20.jpg",
    "images/gold/ladies/mangalsutra/mangalsutra-21.jpg",
    "images/gold/ladies/mangalsutra/mangalsutra-22.jpg",
    "images/gold/ladies/mangalsutra/mangalsutra-23.jpg",
    "images/gold/ladies/mangalsutra/mangalsutra-24.jpg",
    "images/gold/ladies/mangalsutra/mangalsutra-25.jpg",
    "images/gold/ladies/mangalsutra/mangalsutra-26.jpg",
    "images/gold/ladies/mangalsutra/mangalsutra-27.jpg",
    "images/gold/ladies/mangalsutra/mangalsutra-28.jpg",
    "images/gold/ladies/mangalsutra/mangalsutra-29.jpg",
    "images/gold/ladies/mangalsutra/mangalsutra-30.jpg",
    "images/gold/ladies/mangalsutra/mangalsutra-31.jpg",
    "images/gold/ladies/mangalsutra/mangalsutra-32.jpg",
    "images/gold/ladies/mangalsutra/mangalsutra-33.jpg",
    "images/gold/ladies/mangalsutra/mangalsutra-34.jpg",
    "images/gold/ladies/mangalsutra/mangalsutra-35.jpg",
    "images/gold/ladies/mangalsutra/mangalsutra-36.jpg",
    "images/gold/ladies/mangalsutra/mangalsutra-37.jpg",
    "images/gold/ladies/mangalsutra/mangalsutra-38.jpg",
    "images/gold/ladies/mangalsutra/mangalsutra-39.jpg",
    "images/gold/ladies/mangalsutra/mangalsutra-40.jpg",
    "images/gold/ladies/mangalsutra/mangalsutra-41.jpg",
    "images/gold/ladies/mangalsutra/mangalsutra-42.jpg",
    "images/gold/ladies/mangalsutra/mangalsutra-43.jpg",
    "images/gold/ladies/mangalsutra/mangalsutra-44.jpg",
    "images/gold/ladies/mangalsutra/mangalsutra-45.jpg",
    "images/gold/ladies/mangalsutra/mangalsutra-46.jpg",
    "images/gold/ladies/mangalsutra/mangalsutra-47.jpg",
    "images/gold/ladies/mangalsutra/mangalsutra-48.jpg",
    "images/gold/ladies/mangalsutra/mangalsutra-49.jpg",
    "images/gold/ladies/mangalsutra/mangalsutra-50.jpg",
    "images/gold/ladies/mangalsutra/mangalsutra-51.jpg",
    "images/gold/ladies/mangalsutra/mangalsutra-52.jpg",
    "images/gold/ladies/mangalsutra/mangalsutra-53.jpg",
    "images/gold/ladies/mangalsutra/mangalsutra-54.jpg",
    "images/gold/ladies/mangalsutra/mangalsutra-55.jpg",
    "images/gold/ladies/mangalsutra/mangalsutra-56.jpg",
    "images/gold/ladies/mangalsutra/mangalsutra-57.jpg",
    "images/gold/ladies/mangalsutra/mangalsutra-58.jpg",
    "images/gold/ladies/mangalsutra/mangalsutra-59.jpg",
    "images/gold/ladies/mangalsutra/mangalsutra-60.jpg",
    "images/gold/ladies/mangalsutra/mangalsutra-61.jpg",
    "images/gold/ladies/mangalsutra/mangalsutra-62.jpg",
    "images/gold/ladies/mangalsutra/mangalsutra-63.jpg",
    "images/gold/ladies/mangalsutra/mangalsutra-64.jpg",
    "images/gold/ladies/mangalsutra/mangalsutra-65.jpg",
    "images/gold/ladies/mangalsutra/mangalsutra-66.jpg",
    "images/gold/ladies/mangalsutra/mangalsutra-67.jpg",
    "images/gold/ladies/mangalsutra/mangalsutra-68.jpg",
    "images/gold/ladies/mangalsutra/mangalsutra-69.jpg",
    "images/gold/ladies/mangalsutra/mangalsutra-70.jpg",
    "images/gold/ladies/mangalsutra/mangalsutra-71.jpg",
    "images/gold/ladies/mangalsutra/mangalsutra-72.jpg",
    "images/gold/ladies/mangalsutra/mangalsutra-73.jpg",
    "images/gold/ladies/mangalsutra/mangalsutra-74.jpg",
    "images/gold/ladies/mangalsutra/mangalsutra-75.jpg",
    "images/gold/ladies/mangalsutra/mangalsutra-76.jpg",
    "images/gold/ladies/mangalsutra/mangalsutra-77.jpg",
    "images/gold/ladies/mangalsutra/mangalsutra-78.jpg",
    "images/gold/ladies/mangalsutra/mangalsutra-79.jpg",
    "images/gold/ladies/mangalsutra/mangalsutra-80.jpg",
    "images/gold/ladies/mangalsutra/mangalsutra-81.jpg",
    "images/gold/ladies/mangalsutra/mangalsutra-82.jpg",
    "images/gold/ladies/mangalsutra/mangalsutra-83.jpg",
    "images/gold/ladies/mangalsutra/mangalsutra-84.jpg",
    "images/gold/ladies/mangalsutra/mangalsutra-85.jpg"
],

    "necklaces": [
  "images/gold/ladies/necklaces/necklace-01.jpg",
  "images/gold/ladies/necklaces/necklace-02.jpg",
  "images/gold/ladies/necklaces/necklace-03.jpg",
  "images/gold/ladies/necklaces/necklace-04.jpg",
  "images/gold/ladies/necklaces/necklace-05.jpg"
],

      "wrist-watches": [
    "images/gold/ladies/wrist-watches/watch-1.jpg",
    "images/gold/ladies/wrist-watches/watch-2.jpg",
    "images/gold/ladies/wrist-watches/watch-3.jpg",
    "images/gold/ladies/wrist-watches/watch-4.jpg",
    "images/gold/ladies/wrist-watches/watch-5.jpg",
    "images/gold/ladies/wrist-watches/watch-6.jpg",
    "images/gold/ladies/wrist-watches/watch-7.jpg",
    "images/gold/ladies/wrist-watches/watch-8.jpg",
    "images/gold/ladies/wrist-watches/watch-9.jpg",
    "images/gold/ladies/wrist-watches/watch-10.jpg",
    "images/gold/ladies/wrist-watches/watch-11.jpg",
    "images/gold/ladies/wrist-watches/watch-12.jpg",
    "images/gold/ladies/wrist-watches/watch-13.jpg",
    "images/gold/ladies/wrist-watches/watch-14.jpg",
    "images/gold/ladies/wrist-watches/watch-15.jpg",
    "images/gold/ladies/wrist-watches/watch-16.jpg",
    "images/gold/ladies/wrist-watches/watch-20.jpg",
    "images/gold/ladies/wrist-watches/watch-21.jpg",
    "images/gold/ladies/wrist-watches/watch-22.jpg",
    "images/gold/ladies/wrist-watches/watch-23.jpg",
    "images/gold/ladies/wrist-watches/watch-24.jpg",
    "images/gold/ladies/wrist-watches/watch-25.jpg",
    "images/gold/ladies/wrist-watches/watch-26.jpg",
    "images/gold/ladies/wrist-watches/watch-27.jpg",
    "images/gold/ladies/wrist-watches/watch-28.jpg",
    "images/gold/ladies/wrist-watches/watch-29.jpg",
    "images/gold/ladies/wrist-watches/watch-30.jpg",
    "images/gold/ladies/wrist-watches/watch-31.jpg",
    "images/gold/ladies/wrist-watches/watch-32.jpg",
    "images/gold/ladies/wrist-watches/watch-33.jpg",
    "images/gold/ladies/wrist-watches/watch-34.jpg"

],
"i-ring-tops":  [
  "images/gold/ladies/i-ring-tops/i-ring-top-01.jpg",
  "images/gold/ladies/i-ring-tops/i-ring-top-02.jpg",
  "images/gold/ladies/i-ring-tops/i-ring-top-03.jpg",
  "images/gold/ladies/i-ring-tops/i-ring-top-04.jpg"
],
"pendants": [],
"nose-pins": [],
"fancy-jewellery": []
    },


    // ===============================
    // KIDS
    // ===============================

    kids: [ 
  "images/gold/kids/kid-01.jpg",
  "images/gold/kids/kid-02.jpg",
  "images/gold/kids/kid-03.jpg",
  "images/gold/kids/kid-04.jpg",
  "images/gold/kids/kid-05.jpg",
  "images/gold/kids/kid-06.jpg",
  "images/gold/kids/kid-07.jpg",
  "images/gold/kids/kid-08.jpg",
  "images/gold/kids/kid-09.jpg",
  "images/gold/kids/kid-10.jpg",
  "images/gold/kids/kid-11.jpg",
  "images/gold/kids/kid-12.jpg",
  "images/gold/kids/kid-13.jpg",
  "images/gold/kids/kid-14.jpg",
  "images/gold/kids/kid-15.jpg",
  "images/gold/kids/kid-16.jpg",
  "images/gold/kids/kid-17.jpg",
  "images/gold/kids/kid-18.jpg",
  "images/gold/kids/kid-19.jpg",
  "images/gold/kids/kid-20.jpg",
  "images/gold/kids/kid-21.jpg",
  "images/gold/kids/kid-22.jpg",
  "images/gold/kids/kid-23.jpg",
  "images/gold/kids/kid-24.jpg",
  "images/gold/kids/kid-25.jpg",
  "images/gold/kids/kid-26.jpg",
  "images/gold/kids/kid-27.jpg"
],

"i-tops": [],

"pendants": [],

"nose-pins": [],

"fancy-jewellery": [],
  



    // ===============================
    // DEVOTIONAL
    // ===============================

    devotional: [],
// ================================
// DEVOTIONAL
// ================================

devotional: [],


// ================================
// COUPLE RINGS
// ================================

"couple-rings": [
    "images/gold/couple-rings/couple-ring-01.jpg",
    "images/gold/couple-rings/couple-ring-02.jpg",
    "images/gold/couple-rings/couple-ring-03.jpg",
    "images/gold/couple-rings/couple-ring-04.jpg",
    "images/gold/couple-rings/couple-ring-05.jpg",
    "images/gold/couple-rings/couple-ring-06.jpg",
    "images/gold/couple-rings/couple-ring-07.jpg",
    "images/gold/couple-rings/couple-ring-08.jpg",
    "images/gold/couple-rings/couple-ring-09.jpg",
    "images/gold/couple-rings/couple-ring-10.jpg",
    "images/gold/couple-rings/couple-ring-11.jpg",
    "images/gold/couple-rings/couple-ring-12.jpg"
],


// ================================
// PREMIUM COLLECTION
// ================================

"premium-collection": []

},
  // ===============================
  // SILVER
  // ===============================

  silver: {

    // ===============================
    // GENTS
    // ===============================

    gents: {

      rings: [],

      bracelets: [],

      chains: [],

      "single-bali": [],

      "wrist-watches": []

    },


    // ===============================
    // LADIES
    // ===============================

    ladies: {

      rings: [],

      bracelets: [],

      chains: [],

      payal: [],

      "wrist-watches": []

    },


    // ===============================
    // KIDS
    // ===============================

    kids: [],


    // ===============================
    // DEVOTIONAL
    // ===============================

    devotional: [
  "images/silver/devotional/devotional-01.jpg",
  "images/silver/devotional/devotional-02.jpg",
  "images/silver/devotional/devotional-03.jpg",
  "images/silver/devotional/devotional-04.jpg",
  "images/silver/devotional/devotional-05.jpg",
  "images/silver/devotional/devotional-06.jpg",
  "images/silver/devotional/devotional-07.jpg",
  "images/silver/devotional/devotional-08.jpg",
  "images/silver/devotional/devotional-09.jpg",
  "images/silver/devotional/devotional-10.jpg",
  "images/silver/devotional/devotional-11.jpg",
  "images/silver/devotional/devotional-12.jpg",
  "images/silver/devotional/devotional-13.jpg",
  "images/silver/devotional/devotional-14.jpg",
  "images/silver/devotional/devotional-15.jpg",
  "images/silver/devotional/devotional-16.jpg",
  "images/silver/devotional/devotional-17.jpg",
  "images/silver/devotional/devotional-18.jpg",
  "images/silver/devotional/devotional-19.jpg",
  "images/silver/devotional/devotional-20.jpg",
  "images/silver/devotional/devotional-21.jpg",
  "images/silver/devotional/devotional-22.jpg",
  "images/silver/devotional/devotional-23.jpg",
  "images/silver/devotional/devotional-24.jpg",
  "images/silver/devotional/devotional-25.jpg"
]

  }

};

 